config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations] 
  as :user do
    get "users/edit" => "devise/registrations#edit", as: "edit_user_registration"
    patch "users" => "devise/registrations#update", as: "user_registration"
  end
  
  root "static_pages#home"
  
  resources :users, only: [:show, :index]
  resources :user_courses, only: [:show]
  resources :user_subjects, only: [:show, :update]
  resources :user_subjects, only: [:show]
  resources :user_courses, only: [:show]
  resources :relationships, only: [:create, :destroy]
  
  namespace :admin do
    root "courses#index"

    resources :subjects
    resources :courses
    resources :users
    resources :course_subjects, only: [:update, :show]
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :course_subjects, dependent: :destroy
  has_many :user_subjects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :courses, through: :course_subjects
  has_many :users, through: :user_subjects

  accepts_nested_attributes_for :tasks,
    reject_if: ->task{task[:title].blank? || task[:description].blank?},
    allow_destroy: true

  validates :title, presence: true, length: {minimum: 9, maximum: 90}
  validates :description, presence: true, length: {minimum: 9}
  validates :tasks, length: {minimum: 2, message: I18n.t("subject.error.at_least_two_task")}

  def validate_subject subject_params
    number_of_task = 0
    subject_params["tasks_attributes"].each do |key, param|
      if param["_destroy"] == "false" &&
        param[:title].present? && param[:description].present?
          number_of_task += 1
      end
    end
    errors.add :tasks,
      I18n.t("subject.error.at_least_two_task") unless number_of_task > 1
    errors.add :title,
      I18n.t("subject.error.cannot_be_blank") unless subject_params[:title].present?
    errors.add :description,
        I18n.t("subject.error.cannot_be_blank") unless subject_params[:description].present?
  end

  def in_actived_course?
    courses.in_process.any? || courses.closed.any?
  end
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  load_and_authorize_resource

  def index
    @subjects = Subject.paginate page: params[:page],
      per_page: Settings.paginate.number_per_page
  end

  def new
    @subject = Subject.new
    Settings.subject.number_task_default.times do
      @task = @subject.tasks.build
    end
  end

  def edit
  end

  def show
    @tasks = @subject.tasks.paginate page: params[:page],
      per_page: Settings.paginate.number_per_page
  end
  
  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = t "flash.create_success"
      redirect_to admin_subjects_path
    else
      render :new
    end
  end

  def destroy
    if @subject.destroy
      flash[:success] = t "flash.delete_success"
      redirect_to admin_subjects_path
    else
      flash[:danger] = t "flash.delete_failed"
      redirect_to admin_subjects_path
    end
  end

  def update
    @subject.validate_subject subject_params
    if @subject.errors.count > 0
      render :edit
    else
      if @subject.update_attributes subject_params
        flash[:success] = t "flash.update_success"
        respond_to do |format|
          format.html{redirect_to admin_subjects_path}
          format.js
        end
      else
        render :edit
      end
    end
  end

  private
  def subject_params
    params.require(:subject).permit :title, :description,
      tasks_attributes: [:id, :title, :description, :_destroy]
  end
end

app/views/admin/subjects/_form.html.erb
<%= form_for [:admin, @subject], html: {class: "form-horizontal"} do |f| %>
  <%= render "shared/error_notice", object: @subject %>
  <div class="form-group">
    <%= f.label :title, t("form.title"), class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, t("form.description"), class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <h3>
    <%= t("subject.tasks") %>
  </h3>
  <%= f.fields_for :tasks do |builder| %>
    <%= render "admin/subjects/task_fields", f: builder %>
  <% end %>
  <% unless @subject.in_actived_course? %>
    <%= link_to_add_fields t("subject.create_task"), f, :tasks %>
  <% end %>
  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-11">
      <%= f.submit t("form.submit"), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/subjects/_index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>
        <%= t("table.title") %>
      </th>
      <th>
        <%= t("table.option") %>
      </th>
    </tr>
  </thead>
  <tbody>
    <%= render @subjects %>
  </tbody>
</table>
<%= will_paginate @subjects %>

app/views/admin/subjects/_subject.html.erb
<tr>
  <td>
    <%= link_to subject.title, admin_subject_path(subject) %>
  </td>
  <td>
    <%= link_to t("table.delete"), [:admin, subject], method: :delete,
      data: {confirm: t("confirm")} %>
  </td>
  <td>
    <%= link_to t("table.update"), edit_admin_subject_path(subject) %>
  </td>
</tr>

app/views/admin/subjects/_subject_task.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>
        <%= t "table.title" %>
      </th>
      <th>
        <%= t "table.description" %>
      </th>
    </tr>
  </thead>
  <tbody>
    <%= render @tasks %>
  </tbody>
</table>
<%= will_paginate @tasks %>

app/views/admin/subjects/_task_fields.html.erb
<div class="form-task-field">
  <div class="col-sm-12">
    <i class="material-icons">
      <%= f.hidden_field :_destroy %>
      <% unless @subject.in_actived_course? %>
        <%= link_to t("subject.remove_task"), "#", class: "remove_fields" %>
      <% end %>
    </i>
  </div>
  <div class="form-group">
    <%= f.label :title, t("form.title"), class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, t("form.description"), class: "col-sm-1 control-label" %>
    <div class="col-sm-11">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
</div>

app/views/admin/subjects/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3>
        <%= t "subject.update" %>
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12" id="subject-form-update">
      <ul class="alert alert-danger" id="validate-subject">
        <li id="error-number-task"></li>
        <li id="error-subject-title"></li>
        <li id="error-subject-description"></li>
      </ul>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/subjects/index.html.erb
<%= link_to t("subject.create"), new_admin_subject_path, class: "btn btn-primary" %>
<%= link_to t("course.all_course"), admin_courses_path, class: "btn btn-primary" %>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3>
        <%= t "subject.all_subject" %>
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12" id="subject-index">
      <%= render "index" %>
    </div>
  </div>
</div>

app/views/admin/subjects/index.js.erb
$('#subject-index').html('<%= j render "index" %>');
$('.pagination a').attr('data-remote', 'true');

app/views/admin/subjects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3>
        <%= t("subject.create") %>
      </h3>
    </div>
  </div>
  <div class="row">
    <%= render "form" %>
  </div>
</div>

app/views/admin/subjects/show.html.erb
<div class="container">
  <div class="row">
    <h3>
      <%= @subject.title %>
    </h3>
    <br>
    <div class="well">
      <%= @subject.description %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h3>
        <%= t "subject.tasks" %>
      </h3>
    </div>
    <div class="col-sm-12">
      <div id="subject-task">
        <%= render "subject_task" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/subjects/show.js.erb
$('#subject-task').html('<%= j render "subject_task" %>');
$('.pagination a').attr('data-remote', 'true');