config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations] 
  as :user do
    get "users/edit" => "devise/registrations#edit", as: "edit_user_registration"
    patch "users" => "devise/registrations#update", as: "user_registration"
  end
  
  root "static_pages#home"
  
  resources :users, only: [:show, :index]
  resources :user_courses, only: [:show]
  resources :user_subjects, only: [:show, :update]
  resources :user_subjects, only: [:show]
  resources :user_courses, only: [:show]
  resources :relationships, only: [:create, :destroy]
  
  namespace :admin do
    root "courses#index"

    resources :subjects
    resources :courses
    resources :users
    resources :course_subjects, only: [:update, :show]
  end
end

app/models/course_subject.rb
class CourseSubject < ActiveRecord::Base
  enum status: [:free, :in_process, :closed]

  belongs_to :course
  belongs_to :subject

  after_update :change_user_subject_status

  private
  def change_user_subject_status
    if status_changed? && in_process?
      subject.user_subjects.each do |user_subject|
        unless user_subject.finished?
          user_subject.update_attributes status: :in_process
        end
      end
    else
      subject.user_subjects.each do |user_subject|
        unless user_subject.finished?
          user_subject.update_attributes status: :closed
        end
      end
    end
  end
end

app/controllers/admin/course_subjects_controller.rb
class Admin::CourseSubjectsController < ApplicationController
  load_and_authorize_resource

  def update
    if @course_subject.update_attributes course_subject_params
      flash[:success] = t "flash.update_success"
    else
      flash[:danger] = t "flash.update_failed"
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @tasks = @course_subject.subject.tasks.paginate page: params[:page],
      per_page: Settings.paginate.number_per_page
    @courses = @course_subject.subject.courses.paginate page: params[:page_course],
      per_page: Settings.paginate.number_per_page
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def course_subject_params
    params.require(:course_subject).permit :status
  end
end

app/views/admin/course_subjects/_subject_course.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>
        <%= t "table.title" %>
      </th>
      <th colspan="2">
        <%= t "table.description" %>
      </th>
      <th>
        <%= t "table.status" %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td>
          <%= link_to course.title, [:admin, course] %>
        </td>
        <% if can? :manage, :all %>
          <td>
            <%= link_to t("table.update"), edit_admin_course_path(course) %>
          </td>
          <td>
            <%= link_to t("table.delete"), [:admin, course], method: :delete,
              data: {confirm: t("confirm")} %>
          </td>
        <% end %>
        <td>
          <%= course.status %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @courses, param_name: :page_course %>

app/views/admin/course_subjects/show.html.erb
<div class="container">
  <div class="row">
    <h3>
      <%= @course_subject.subject.title %>
    </h3>
    <br>
    <div class="well">
      <%= @course_subject.subject.description %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h3>
        <%= t "subject.tasks" %>
      </h3>
    </div>
    <div class="col-sm-12">
      <div id="subject-task">
        <%= render "subject_task" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h3>
        <%= t "subject.appears_in_course" %>
      </h3>
    </div>
    <div class="col-sm-12">
      <div id="subject-course">
        <%= render "subject_course" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/course_subjects/show.js.erb
$('#subject-task').html('<%= j render "subject_task" %>');
$('#subject-course').html('<%= j render "subject_course" %>');
$('.pagination a').attr('data-remote', 'true');

app/views/admin/course_subjects/update.js.erb
$('#course-subject-status-form-<%= @course_subject.id %>')
  .html('<%= j render "admin/courses/status_subject_form", course_subject: @course_subject %>');
$('#flash-notice').html('<%= j render "layouts/flash" %>');
<% flash.clear %>