config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations] 
  as :user do
    get "users/edit" => "devise/registrations#edit", as: "edit_user_registration"
    patch "users" => "devise/registrations#update", as: "user_registration"
  end
  
  root "static_pages#home"
  
  resources :users, only: [:show, :index]
  resources :user_courses, only: [:show]
  resources :user_subjects, only: [:show, :update]
  resources :user_subjects, only: [:show]
  resources :user_courses, only: [:show]
  resources :relationships, only: [:create, :destroy]
  
  namespace :admin do
    root "courses#index"

    resources :subjects
    resources :courses
    resources :users
    resources :course_subjects, only: [:update, :show]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :rememberable, :validatable, :timeoutable

  enum role: [:trainee, :supervisor, :admin]

  has_many :user_courses, dependent: :destroy
  has_many :user_subjects, dependent: :destroy
  has_many :user_tasks, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :courses, through: :user_courses
  has_many :subjects, through: :user_subjects
  has_many :tasks, through: :user_tasks
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  scope :not_admin, ->{where.not role: User.roles[:admin]}
  scope :not_in_actived_course, ->{where("id NOT IN
    (SELECT user_id FROM user_courses
    WHERE status = #{Course.statuses[:in_process]})
    OR id IN(SELECT id FROM users
    WHERE(role = #{User.roles[:supervisor]}))")}
  scope :not_in_other_actived_course, ->course{where("id NOT IN
    (SELECT user_id FROM user_courses
    WHERE(status = #{Course.statuses[:in_process]}))
    OR id IN(SELECT id FROM users WHERE role = #{User.roles[:supervisor]})
    OR id IN(SELECT user_id FROM user_courses
    WHERE course_id = #{course.id})")}
  scope :order_by_supervisor, ->{order role: :desc}
  scope :in_other_actived_course, ->course{where("id IN
    (SELECT user_id FROM user_courses
    WHERE(course_id NOT IN(#{course.id})
    AND status = #{Course.statuses[:in_process]})
    AND user_id IN(SELECT user_id FROM user_courses
    WHERE course_id = #{course.id}))")}
  scope :not_finished_with_current_course, ->course{where("id NOT IN
    (SELECT user_id FROM user_courses
    WHERE course_id = #{course.id}
    AND status = #{UserCourse.statuses[:finished]})")}
  
  validates :name, presence: true, length: {minimum: 6, maximum: 20}
  validates :role, presence: true

  mount_uploader :avatar, AvatarUploader
  after_update :create_activity

  def is_user? user
    self == user
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
    Activity.create user_id: id,
      action_type: Activity.action_types[:follow], target_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
    Activity.create user_id: id,
      action_type: Activity.action_types[:unfollow], target_id: other_user.id
  end

  def following? other_user
    following.include? other_user
  end

  def is_supervisor_in_actived_course?
    supervisor? && !user_courses.in_process.empty?
  end

  def create_activity
    Activity.create user_id: id,
      action_type: Activity.action_types[:update_profile]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource
  
  def index
  end

  def create
    if @user.save
      flash[:success] = t "flash.create_success"
      redirect_to admin_users_path
    else
      render :new
    end
  end
  
  def edit
    @actived_courses = @user.user_courses.in_process if @user.supervisor?
  end
 
  def update
    if @user.update_attributes user_params
      flash[:success] = t "flash.update_success"
      redirect_to admin_users_path
    else
      flash[:danger] = t "flash.update_failed"
      render :edit
    end
  end
  
  def destroy
    if @user.destroy
      flash[:success] = t "flash.delete_success"
      redirect_to admin_users_path
    else
      flash[:danger] = t "flash.delete_failed"
      redirect_to admin_users_path
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password, :role
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.trainee
  end

  def show
    @user_courses = @user.user_courses
    @activities = @user.activities.latest
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_course_status user_course
    if current_user.supervisor?
      link_to user_course.course.title,
        [:admin, user_course.course], class: "btn btn-primary"
    else
      if user_course.finished?
        link_to user_course.course.title,
          user_course_path(user_course), class: "btn btn-success"
      elsif user_course.free?
        content_tag :div, user_course.course.title, class: "btn btn-default"
      elsif user_course.in_process?
        link_to user_course.course.title,
          user_course_path(user_course), class: "btn btn-primary"
      else
        link_to user_course.course.title,
          user_course_path(user_course), class: "btn btn-warning"
      end
    end
  end

  def user_subject_status user_subject
    if user_subject.finished?
      link_to user_subject.subject.title,
        user_subject_path(user_subject), class: "btn btn-success"
    elsif user_subject.free?
      content_tag :div, user_subject.subject.title, class: "btn btn-default"
    elsif user_subject.in_process?
      link_to user_subject.subject.title,
        user_subject_path(user_subject), class: "btn btn-primary"
    else
      link_to user_subject.subject.title,
        user_subject_path(user_subject), class: "btn btn-warning"
    end
  end

  def activity_action activity
    if activity.update_profile?
      content_tag :div, t("activity.update_profile",
        time: time_ago_in_words(activity.created_at))
    elsif activity.follow?
      following_user = User.find_by id: activity.target_id
      content_tag :div, t("activity.follow_html", 
        user: link_to(following_user.name,
          user_path(following_user),
          class: "label label-info"),
        time: time_ago_in_words(activity.created_at))
    elsif activity.unfollow?
      unfollow_user = User.find_by id: activity.target_id
      content_tag :div, t("activity.unfollow_html",
        user: link_to(unfollow_user.name, 
          user_path(unfollow_user),
          class: "label label-info"),
        time: time_ago_in_words(activity.created_at))
    elsif activity.finish_task?
      user_task = UserTask.find_by id: activity.target_id
      content_tag :div, t("activity.finish_task_html",
        user: link_to(activity.user.name, activity.user),
        task: link_to(user_task.task.title, user_task.user_subject, 
          class: "label label-info"),
        time: time_ago_in_words(activity.created_at))
    elsif activity.finish_subject?
      user_subject = UserSubject.find_by id: activity.target_id
      content_tag :div, t("activity.finish_subject_html", 
        user: link_to(activity.user.name, activity.user),
        subject: link_to(user_subject.subject.title, user_subject,
          class: "label label-info"),
        time: time_ago_in_words(activity.created_at))
    else activity.finish_course?
      user_course = UserCourse.find_by id: activity.target_id
      content_tag :div, t("activity.finish_course_html",
        user: link_to(activity.user.name, activity.user),
        course: link_to(user_course.course.title, user_course,
          class: "label label-info"),
        time: time_ago_in_words(activity.created_at))
    end        
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], html: {class: "form-horizontal"} do |f| %>
  <%= render "shared/error_notice", object: @user %>
  <% if can? :manage, :all %>
    <div class="form-group">
      <%= f.label :name, t("form.name"), class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, t("form.email"), class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
        <%= f.email_field :email, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password, t("form.password"), class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
        <%= f.password_field :password, class: "form-control" %>
      </div>
    </div>
    <div class="field">
      <% unless @user.is_supervisor_in_actived_course? %>
        <%= f.label :role, t("form.trainee") %>
        <%= f.radio_button :role, :trainee %>
      <% end %>
      <%= f.label :role, t("form.supervisor") %>
      <%= f.radio_button :role, :supervisor %>
    </div>
    <br>
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-11">
        <%= f.submit t("form.submit"), class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3>
        <%= t "user.update" %>
      </h3>
    </div>
  </div>
  <div class="row">
    <% if @user.is_supervisor_in_actived_course? %>
      <h4><%=  t("user.joinning_course", user_name: @user.name) %>
        <% @actived_courses.each do |actived_course| %>
          <%= link_to actived_course.course.title,  
            admin_course_path(actived_course.course) %>
        <% end %>
      </h4>
    <% end %>
  </div>
  <div class="row">
    <%= render "form" %>
  </div>

</div>

app/views/admin/users/index.html.erb
<% if can? :manage, :all %>
  <%= link_to t("user.create"), new_admin_user_path, class: "btn btn-primary" %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>
        <%= t "user.name" %>
      </th>
      <th>
        <%= t "user.email" %>
      </th>
      <th>
        <%= t "user.role" %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user|%>
      <tr>
        <td>
          <%= link_to user.name, user_path(user) %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= user.role %>
        </td>
        <% if can? :manage, :all %>
          <td>
            <%= link_to t("table.update"), edit_admin_user_path(user) %>
          </td>
          <td>
            <%= link_to t("table.delete"), [:admin, user], method: :delete,
              data: {confirm: t("confirm")} %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  
</table>

app/views/admin/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3>
        <%= t "user.create" %>
      </h3>
    </div>
  </div>
  <div class="row">
    <%= render "form" %>
  </div>
</div>